#server:
#  port: 60005
#
#
#spring:
#  main:
#    allow-bean-definition-overriding: true
#  application:
#    name: bdmp-public
#  cloud:
#    nacos:
#      discovery:
#        server-addr: http://172.16.10.100:8848
#  datasource:
#    multiple-datasource:
#      - name: default
#        driverClassName: com.mysql.jdbc.Driver
#        url: jdbc:mysql://172.16.10.100:3306/bdmp_server?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&failOverReadOnly=false
#        username: root
#        password: 123456
#        # 初始连接数
#        hikari:
#          initial-size: 5
#          # 最小连接数
#          min-idle: 10
#          # 最大连接数
#          max-active: 50
#
#
#
## mybatis-plus配置
#mybatis-plus:
#  mapper-locations: classpath:mapper/**/*.xml
#  #实体扫描，多个package用逗号或者分号分隔
#  type-aliases-package: com.rhy.bdmp.open.modules.*.domain.po
#  global-config:
#    db-config:
#      #主键类型  0:"数据库ID自增",1:"无主键设置",2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID";
#      id-type: ASSIGN_ID
#      #是否开启大写命名，默认不开启
#      capital-mode: true
#      #逻辑删除配置
#      logic-delete-value: 0
#      logic-not-delete-value: 1
#  configuration:
#    map-underscore-to-camel-case: true
#    cache-enabled: false
#    call-setters-on-nulls: true
#    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#feign:
#  httpclient:
#    enabled: true
#  okhttp:
#    enabled: false
#  client:
#    config:
#      default:
#        requestInterceptors: com.rhy.bdmp.open.modules.filter.FeignBasicAuthRequestInterceptor
#
#
## 全局参数设置
#ribbon:
#  ReadTimeout: 120000
#  ConnectTimeout: 10000
#  SocketTimeout: 10000
#  MaxAutoRetries: 0
#  MaxAutoRetriesNextServer: 1
#
#custom:
#  file:
#    downUrl: http://127.0.0.1:60000/bdmp/system/sys/plupload/showImg?fileId=